rule_files:
- toy_alerts.yaml

tests:
- interval: 1m
  input_series:
  - series: problem_counter{reason="TempProblem2", nodeName="a"}
    values: 5x10
  - series: problem_counter{reason="TempProblem2", nodeName="b"}
    values: 5 6 7 5 5 7 8 9

  alert_rule_test:
  - eval_time: 1m
    alertname: ProblemCounterHigh
  - eval_time: 2m
    alertname: ProblemCounterHigh
    exp_alerts:
    - exp_labels:
        severity: critical
        reason: TempProblem2
        nodeName: b
      exp_annotations:
        message: "Problem counter high on b: 7"
        test: "This is an external label: test"
  - eval_time: 3m
    alertname: ProblemCounterHigh
  - eval_time: 5m
    alertname: ProblemCounterHigh
  - eval_time: 6m
    alertname: ProblemCounterHigh
    exp_alerts:
    - exp_labels:
        severity: critical
        reason: TempProblem2
        nodeName: b
      exp_annotations:
        message: "Problem counter high on b: 8"
        test: "This is an external label: test"
  - eval_time: 7m
    alertname: ProblemCounterHigh
    exp_alerts:
    - exp_labels:
        severity: critical
        reason: TempProblem2
        nodeName: b
      exp_annotations:
        message: "Problem counter high on b: 9"
        test: "This is an external label: test"

  external_labels:
    cluster: test
