apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
      tolerations:
      - key: playground_test
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        mock-server: "true"
      containers:
      - image: mock-server:0.0.1
        name: {{ .Release.Name }}
        securityContext:
          runAsUser: 9999
          runAsGroup: 9999
        volumeMounts:
        - mountPath: /test-tmp
          name: host-tmp
        - mountPath: /app/certs
          name: certs
      - image: busybox
        name: busybox
        command: ["/bin/sh", "-c", "while :; do echo '.'; sleep 30 ; done"]
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: host-tmp
        hostPath:
          path: /tmp
          type: Directory
      - name: certs
        secret:
          secretName: {{ .Release.Name }}-certs
