apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certs
data:
  cert.pem: {{ .Files.Get "server/certs/cert.pem" | b64enc | quote }}
  key.pem: {{ .Files.Get "server/certs/key.pem" | b64enc | quote }}
