apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:7.0.9
    init: confluentinc/confluent-init-container:2.2.0-1
  externalAccess:
    nodePort:
      host: localhost
      nodePortOffset: 31010
    type: nodePort
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfig:
          secretRef: {{ template "schema-registry-jaas-secret-name" }}
