apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-monitor-name" }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "kafka-monitor-name" }}
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: metrics
    protocol: TCP
    port: {{ template "kafka-monitor-metrics-port" }}
    targetPort: {{ template "kafka-monitor-metrics-port" }}
