apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels: {{ .Values.labels | toYaml | nindent 4 }}
spec:
  endpoints:
  - port: {{ .Values.metrics_port_name }}
    metricRelabelings:
    - action: labelkeep
      regex: __name__|endpoint|nodeName|reason|service|env
    - targetLabel: test
      replacement: test
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: nodeName
    - targetLabel: env
      replacement: dev
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels: {{ .Values.labels | toYaml | nindent 6 }}
