kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: clusterrole
  apiGroup: rbac.authorization.k8s.io
