kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding1
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: kube-system-sa
roleRef:
  kind: Role
  name: role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding2
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: kube-system-sa
roleRef:
  kind: ClusterRole
  name: clusterrole
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding3
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: default-sa
    namespace: default
roleRef:
  kind: Role
  name: role
  apiGroup: rbac.authorization.k8s.io
