name=standalone-mm2-source
connector.class=org.apache.kafka.connect.mirror.MirrorSourceConnector
tasks.max=5
topics=test_topic.*

source.cluster.alias=upstream
source.cluster.bootstrap.servers=localhost:31000
source.cluster.security.protocol=SASL_PLAINTEXT
source.cluster.sasl.mechanism=PLAIN
source.cluster.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="test1" password="password1";

target.cluster.bootstrap.servers=localhost:31000
target.cluster.security.protocol=SASL_PLAINTEXT
target.cluster.sasl.mechanism=PLAIN
target.cluster.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="test1" password="password1";

sync.group.offsets=false
emit.checkpoints.enabled=false
