elasticsearch:
  antiAffinity: soft
  tolerations:
  - key: playground_test
    operator: Exists
    effect: NoSchedule
  esConfig:
    elasticsearch.yml: |
      xpack:
        monitoring:
          collection:
            enabled: true

kibana:
  httpPort: 5601
  kibanaConfig:
    kibana.yml: |
      server:
        basePath: /kibana

fluent-bit:
  image:
    pullPolicy: IfNotPresent
    tag: 1.5.6
  tolerations:
  - operator: Exists
  serviceMonitor:
    enabled: true
  extraVolumes:
  - configMap:
      defaultMode: 420
      name: fluent-bit-functions
    name: functions
  extraVolumeMounts:
  - mountPath: /fluent-bit/etc/functions.lua
    name: functions
    subPath: functions.lua

  functions: |
    function dedot(tag, timestamp, record)
        if record["kubernetes"] == nil then
            return 0, 0, 0
        end
        dedot_keys(record["kubernetes"]["annotations"])
        dedot_keys(record["kubernetes"]["labels"])
        return 1, timestamp, record
    end

    function dedot_keys(map)
        if map == nil then
            return
        end
        local new_map = {}
        local changed_keys = {}
        for k, v in pairs(map) do
            local deslashed = string.gsub(k, "%/", "_")
            local dedotted = string.gsub(deslashed, "%.", "_")
            if dedotted ~= k then
                new_map[dedotted] = v
                changed_keys[k] = true
            end
        end
        for k in pairs(changed_keys) do
            map[k] = nil
        end
        for k, v in pairs(new_map) do
            map[k] = v
        end
    end

    function remove_annotations(tag, timestamp, record)
        if record["kubernetes"] == nil then
            return 0, 0, 0
        end
        if record["kubernetes"]["annotations"] == nil then
            return 0, 0, 0
        end
        record["kubernetes"]["annotations"] = nil
        return 1, timestamp, record
    end

  config:
    service: |
      [SERVICE]
          Flush         5
          Daemon        Off
          Log_Level     info
          Parsers_File  parsers.conf
          HTTP_Server   On
          HTTP_Listen   0.0.0.0
          HTTP_Port     2020

    inputs: |
      [INPUT]
          Name             tail
          Path             /var/log/containers/*.log
          Tag              kube.*
          Mem_Buf_Limit    5MB
          Skip_Long_Lines  On
          Parser           cri

    filters: |
      [FILTER]
          Name                 kubernetes
          Match                kube.*
          Merge_Log            On
          Keep_Log             Off
          K8S-Logging.Parser   On
          K8S-Logging.Exclude  On
          Annotations          On
      [FILTER]
          Name    lua
          Match   kube.*
          script  /fluent-bit/etc/functions.lua
          call    dedot
      [FILTER]
          Name          rewrite_tag
          Match         kube.*
          Rule          $kubernetes['annotations']['loggingTag'] .* kube_$kubernetes['annotations']['loggingTag'] false
          Emitter_Name  special_rewriter
      [FILTER]
          Name          rewrite_tag
          Match         kube.*
          Rule          $kubernetes['namespace_name'] ^(kube-system)$ kube_system false
          Emitter_Name  system_rewriter
      [FILTER]
          Name          rewrite_tag
          Match         kube_system
          Rule          $kubernetes['container_name'] ^(public)$ public_index false
          Emitter_Name  public_rewriter
      [FILTER]
          Name    lua
          Match   *
          script  /fluent-bit/etc/functions.lua
          call    remove_annotations

    outputs: |
      [OUTPUT]
          Name             es
          Match            kube.*
          Host             elasticsearch-master
          Logstash_Format  On
          Logstash_Prefix  fluent-general
          Retry_Limit      False
      [OUTPUT]
          Name             es
          Match            kube_system
          Host             elasticsearch-master
          Logstash_Format  On
          Logstash_Prefix  fluent-system
          Retry_Limit      False
      [OUTPUT]
          Name             es
          Match            kube_special
          Host             elasticsearch-master
          Logstash_Format  On
          Logstash_Prefix  fluent-special
          Retry_Limit      False
      [OUTPUT]
          Name             es
          Match            public_index
          Host             elasticsearch-master
          Logstash_Format  On
          Logstash_Prefix  fluent-public
          Retry_Limit      False

fluentBitSidecar:
  appName: logging-sidecar-test
  configmapName: fluent-bit-sidecar-cm
  namespace: default
  config: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        Parsers_File  custom_parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /logs/public/*.log
        Tag               public.*
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Multiline         On
        Parser_Firstline  multiline
    [INPUT]
        Name             tail
        Path             /logs/protected/*.log
        Tag              protected.*
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On

    [FILTER]
        Name    record_modifier
        Match   *
        Record  kubernetes.host ${POD_NODE}
        Record  kubernetes.pod_name ${POD_NAME}
        Record  kubernetes.namespace_name ${POD_NAMESPACE}
        Record  app.name ${APP_NAME}
    [FILTER]
        Name    lua
        Match   *
        script  /fluent-bit/etc/functions.lua
        call    add_tag_to_record

    [OUTPUT]
        Name             es
        Match            public.*
        Host             elasticsearch-master.kube-system.svc.cluster.local
        Logstash_Format  On
        Logstash_Prefix  sidecar-public
        Retry_Limit      False
    [OUTPUT]
        Name             es
        Match            protected.*
        Host             elasticsearch-master.kube-system.svc.cluster.local
        Logstash_Format  On
        Logstash_Prefix  sidecar-protected
        Retry_Limit      False

  parsers: |
    [PARSER]
        Name    multiline
        Format  regex
        Regex   ^\d+\/\d+\/\d+ \d+\:\d+\:\d+ - (?<log>.*)$

  functions: |
    function add_tag_to_record(tag, timestamp, record)
        record["tag"] = tag
        return 1, timestamp, record
    end

prometheus-elasticsearch-exporter:
  serviceMonitor:
    enabled: true
  es:
    uri: http://elasticsearch-master.kube-system.svc.cluster.local:9200
