apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
rules:
  - apiGroups:
      - '*'
    resources:
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - '*'
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
