apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.fluentBitSidecar.appName }}
  namespace: {{ .Values.fluentBitSidecar.namespace }}
spec:
  replicas: 1
  serviceName: {{ .Values.fluentBitSidecar.appName }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.fluentBitSidecar.appName }}
  template:
    metadata:
      annotations:
        loggingTag: special
      labels:
        app.kubernetes.io/name: {{ .Values.fluentBitSidecar.appName }}
    spec:
      initContainers:
      - image: python:2.7-alpine
        name: log-cleaner
        command:
        - "sh"
        - "-c"
        - "rm -rf /logs/*"
        volumeMounts:
        - mountPath: /logs
          name: logs
      containers:
      - image: log-generator:0.0.1
        name: log-generator
        args:
        - "/logs"
        volumeMounts:
        - mountPath: /logs
          name: logs
      - image: fluent/fluent-bit:{{ (index .Values "fluent-bit").image.tag }}-debug
        command:
        - "sh"
        - "-c"
        - "trap 'echo SIGTERM received' TERM; /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf;"
        name: fluent-bit
        volumeMounts:
        - mountPath: /logs
          name: logs
        - mountPath: /fluent-bit/etc/fluent-bit.conf
          name: fluent-bit
          subPath: config
        - mountPath: /fluent-bit/etc/custom_parsers.conf
          name: fluent-bit
          subPath: parsers
        - mountPath: /fluent-bit/etc/functions.lua
          name: fluent-bit
          subPath: functions
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: APP_NAME
          value: {{ .Values.fluentBitSidecar.appName }}
        ports:
        - containerPort: 2020
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Values.fluentBitSidecar.configmapName }}
        name: fluent-bit
  volumeClaimTemplates:
  - metadata:
      name: logs
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 10Mi
